jobs: 
  build: 
    docker: 
      - 
        image: "cimg/base:stable"
    steps: 
      - node/install
      - eb/setup
      - aws-cli/setup
      - checkout
      - 
        run: 
          command: "npm run frontend:install\n"
          name: "Front-End Install"
      - 
        run: 
          command: "npm run api:install\n"
          name: "Back-End Install"
      - 
        run: 
          command: "npm run frontend:build\n"
          name: "Front-End Build"
      - 
        run: 
          command: "npm run api:build\n"
          name: "Back-End Build"
      - 
        run: 
          command: |
              npm run frontend:deploy
              npm run api:deploy
          name: "Deploy App"
orbs: 
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.2
version: 2.1
workflows: 
  jobs: 
    - build
    - 
      hold: 
        filters: 
          branches: 
            only: 
              - master
        requires: 
          - build
        type: approval
    - 
      deploy: 
        requires: 
          - hold
